spring:
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/joo
    username: root
    #password: joo123
    #test-whileIdle: true
    #validationQuery: select 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true